### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by Goddak** [legomushroom/resize#5]
Just stumbled across this and it would have been perfect for what I needed however it seems as though it no longer works (I couldn't even get the sandbox going).. I'm guessing this won't be updated (hasn't been for years) so maybe update the README.md? Just to say `Deprecated` somewhere high up and save future people a few seconds?

**Comment by legomushroom** [comment]
@Goddak thanks for the feedback! I've archived the issue as it is indeed no longer supported. Cheers!
